version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bagel-store-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bagel-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bagel-store-app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dev
      FLASK_ENV: development
      SECRET_KEY: test-secret-key
    ports:
      - "5001:5000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - bagel-network

networks:
  bagel-network:
    driver: bridge
